spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
      redis:
        password: ${SPRING_DATA_REDIS_PASSWORD}
  session:
    cookie:
      http-only: true
      secure: true
      same-site: strict

storefront:
  public-origin: ${STOREFRONT_PUBLIC_ORIGIN}
