CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT chk_account_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE UNIQUE INDEX uk_account_email_case_insensitive
    ON account (LOWER(BTRIM(email)));

ALTER TABLE account
    ADD CONSTRAINT uk_account_id_role UNIQUE (id, role);

CREATE TABLE customer (
    account_id BIGINT NOT NULL,
    account_role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
    CONSTRAINT pk_customer PRIMARY KEY (account_id),
    CONSTRAINT chk_customer_account_role CHECK (account_role = 'CUSTOMER'),
    CONSTRAINT fk_customer_account
        FOREIGN KEY (account_id, account_role) REFERENCES account (id, role)
);

CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    recipient_name VARCHAR(200) NOT NULL,
    company_name VARCHAR(200),
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255),
    city VARCHAR(100),
    region VARCHAR(100),
    postal_code VARCHAR(32),
    country_code CHAR(2),
    phone_number VARCHAR(32),
    is_default_shipping BOOLEAN NOT NULL DEFAULT FALSE,
    is_default_billing BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT chk_address_country_code
        CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT fk_address_customer
        FOREIGN KEY (customer_id) REFERENCES customer (account_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_address_default_shipping
    ON address (customer_id)
    WHERE is_default_shipping;

CREATE UNIQUE INDEX uk_address_default_billing
    ON address (customer_id)
    WHERE is_default_billing;
