CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL,
    given_name VARCHAR(100) NOT NULL,
    family_name VARCHAR(100) NOT NULL,
    contact_email VARCHAR(254) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version    BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT pk_customer PRIMARY KEY (id),
    CONSTRAINT uk_customer_account UNIQUE (account_id)
);

CREATE INDEX ix_customer_created_at ON customer (created_at DESC, id DESC);

CREATE TABLE address
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id         BIGINT       NOT NULL,
    recipient_name      VARCHAR(200) NOT NULL,
    company_name        VARCHAR(200),
    address_line_1      VARCHAR(255) NOT NULL,
    address_line_2      VARCHAR(255),
    city                VARCHAR(100) NOT NULL,
    region              VARCHAR(100),
    postal_code         VARCHAR(32)  NOT NULL,
    country_code        CHAR(2)      NOT NULL,
    phone_number        VARCHAR(32),
    is_default_shipping BOOLEAN      NOT NULL DEFAULT FALSE,
    is_default_billing  BOOLEAN      NOT NULL DEFAULT FALSE,
    version             BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT fk_address_customer
        FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_address_default_shipping
    ON address (customer_id)
    WHERE is_default_shipping;

CREATE UNIQUE INDEX uk_address_default_billing
    ON address (customer_id)
    WHERE is_default_billing;
