CREATE TABLE catalog_attribute_definition
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(80)  NOT NULL,
    label       VARCHAR(120) NOT NULL,
    value_type  VARCHAR(20)  NOT NULL,
    scope       VARCHAR(20)  NOT NULL,
    is_option   BOOLEAN      NOT NULL DEFAULT FALSE,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_catalog_attribute_definition PRIMARY KEY (id),
    CONSTRAINT uk_catalog_attribute_definition_code UNIQUE (code),
    CONSTRAINT chk_catalog_attribute_definition_type CHECK (value_type IN ('TEXT', 'NUMBER', 'BOOLEAN', 'SELECT')),
    CONSTRAINT chk_catalog_attribute_definition_scope CHECK (scope IN ('PRODUCT', 'VARIANT')),
    CONSTRAINT chk_catalog_attribute_definition_option CHECK (NOT is_option OR value_type = 'SELECT')
);

CREATE TABLE catalog_attribute_allowed_value
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    definition_id  BIGINT       NOT NULL,
    code           VARCHAR(80)  NOT NULL,
    label          VARCHAR(120) NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_catalog_attribute_allowed_value PRIMARY KEY (id),
    CONSTRAINT uk_catalog_attribute_allowed_value_code UNIQUE (definition_id, code),
    CONSTRAINT fk_catalog_attribute_allowed_value_definition
        FOREIGN KEY (definition_id) REFERENCES catalog_attribute_definition (id) ON DELETE CASCADE
);

CREATE TABLE product_attribute_assignment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id      BIGINT      NOT NULL,
    definition_id   BIGINT      NOT NULL,
    text_value      TEXT,
    number_value    NUMERIC(19, 6),
    boolean_value   BOOLEAN,
    select_value_id BIGINT,
    CONSTRAINT pk_product_attribute_assignment PRIMARY KEY (id),
    CONSTRAINT uk_product_attribute_assignment_definition UNIQUE (product_id, definition_id),
    CONSTRAINT fk_product_attribute_assignment_product
        FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_attribute_assignment_definition
        FOREIGN KEY (definition_id) REFERENCES catalog_attribute_definition (id),
    CONSTRAINT fk_product_attribute_assignment_value
        FOREIGN KEY (select_value_id) REFERENCES catalog_attribute_allowed_value (id),
    CONSTRAINT chk_product_attribute_assignment_one_value CHECK (
        (CASE WHEN text_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN number_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN boolean_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN select_value_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
);

CREATE TABLE product_variant_attribute_assignment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    variant_id      BIGINT      NOT NULL,
    definition_id   BIGINT      NOT NULL,
    text_value      TEXT,
    number_value    NUMERIC(19, 6),
    boolean_value   BOOLEAN,
    select_value_id BIGINT,
    CONSTRAINT pk_product_variant_attribute_assignment PRIMARY KEY (id),
    CONSTRAINT uk_product_variant_attribute_assignment_definition UNIQUE (variant_id, definition_id),
    CONSTRAINT fk_product_variant_attribute_assignment_variant
        FOREIGN KEY (variant_id) REFERENCES product_variant (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_variant_attribute_assignment_definition
        FOREIGN KEY (definition_id) REFERENCES catalog_attribute_definition (id),
    CONSTRAINT fk_product_variant_attribute_assignment_value
        FOREIGN KEY (select_value_id) REFERENCES catalog_attribute_allowed_value (id),
    CONSTRAINT chk_product_variant_attribute_assignment_one_value CHECK (
        (CASE WHEN text_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN number_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN boolean_value IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN select_value_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    )
);
